# Generated by Django 4.2.1 on 2024-01-23 01:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_aboutmodle_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=10, null=True)),
                ("lastname", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=500, null=True)),
                ("meassage", models.TextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
